name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["7.4", "8.0"]
        include:
          - php: "7.4"
            phpstan_config: "-c phpstan-php7.neon"
            require_checker_config: "--config-file=composer-require-checker-php7.json"
            infection_score: "--min-msi=92 --min-covered-msi=96"

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-${{ matrix.php }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          mkdir -p /root/.ssh
          ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
          composer self-update --2
          echo "COMPOSER_CACHE=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer-v2

      - name: Install dependencies
        run: |
          composer update --no-progress --no-suggest --no-interaction > /dev/null

      - name: Static analysis
        run: |
          composer check-deps -- ${{ matrix.require_checker_config }}
          composer cs-check
          composer phpstan -- --no-progress ${{ matrix.phpstan_config }}

      - name: Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --stop-on-failure
          composer run --timeout=0 infection -- ${{ matrix.infection_score }}

      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage.xml"
          comment_context: PHP ${{ matrix.php }}
          threshold_alert: 95
          threshold_warning: 100
